spring:
  application.name: thumb-backend
  mvc:
    servlet:
      path: /api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/thumb_db
    username: root
    password: XXXXXXXXXX
  data:
    redis:
      database: 0
      host: localhost
      password: XXXXXXXXXX
      port: 6379
      timeout: 5000

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

knife4j:
  enable: true
  setting:
    language: zh_cn

